### ISSUE TITLE
pip install git+https://github.com/lukemelas/pytorch-pretrained-gans

### ISSUE THREAD

**Issue by ModMorph** [lukemelas/unsupervised-image-segmentation#1]
Hi, is the repo in the pytorch-pretrained-gans step public or is that the right URL for it?  I got prompted for username and password when I tried the pip install git+ and don't see the repo at that URL: https://github.com/lukemelas/pytorch-pretrained-gans 
(Get 404)

Thanks.

**Comment by lukemelas** [comment]
My apologies! I made this repo public, but I did not make the pytorch-pretrained-gans repo public! You should be able to access it now. 

Let me know if you have any issues.

**Comment by ModMorph** [comment]
Thanks! Able to git and install now.
