### ISSUE TITLE
A question about the pretrain of GAN

### ISSUE THREAD

**Issue by minilionChang** [lukemelas/unsupervised-image-segmentation#2]
Hello,
Do you have pretraining the GAN on the CUB, Flowers datasets when you want to train a segmenter for CUB, Flowers datasets?

**Comment by lukemelas** [comment]
Hello,

If I understand your question correctly, you're asking if it's necessary to pretrain a GAN on Flowers/CUB in order to segment Flowers/CUB. The answer is no, you don't :) . You can use an ImageNet-pretrained GAN and simply segment images from Flowers/CUB ("zero-shot") with the same model.

**Comment by minilionChang** [comment]
> Hello,
> 
> If I understand your question correctly, you're asking if it's necessary to pretrain a GAN on Flowers/CUB in order to segment Flowers/CUB. The answer is no, you don't :) . You can use an ImageNet-pretrained GAN and simply segment images from Flowers/CUB ("zero-shot") with the same model.

THanks for your reply!

**Comment by lukemelas** [comment]
Of course! Happy to help.
