### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Lee-Gao** [lukemelas/unsupervised-image-segmentation#3]
Firstly, I ran `PYTHONPATH=. python optimization/main.py data_gen/generator=bigbigan name=NAME`. 
And then, I ran `PYTHONPATH=. python segmentation/generate_and_save.py \
name=NAME \
data_gen=generated \
data_gen/generator=bigbigan \
data_gen.checkpoint="YOUR_OPTIMIZATION_DIR_FROM_ABOVE/latest.pth" \
data_gen.save_dir="YOUR_OUTPUT_DIR" \
data_gen.save_size=1000000 \
data_gen.kwargs.batch_size=1 \
data_gen.kwargs.generation_batch_size=128`
When I ran `PYTHONPATH=. python segmentation/main.py \
name=NAME \
data_gen=saved \
data_gen.data.root="YOUR_OUTPUT_DIR_FROM_ABOVE"`
An error occurred. The error is:
 `Traceback (most recent call last):
  File "segmentation/main.py", line 98, in main
    kwargs = dict(images_dir=_cfg.images_dir, labels_dir=_cfg.labels_dir,
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable '/raid/name/gaochengli/segmentation/src/images' not found"
    full_key: data_seg.data[0].images_dir
    object_type=dict`
According to what you wrote, I modified the root (config/segment.yaml on line 19). Just like this "/raid/name/gaochengli/segmentation/src/images". And the folder contains all data sets,whose name is images.
I wonder why such a mistake happened.

**Comment by songtaoye9** [comment]
> 
Do you fix this bug?

**Comment by ghost** [comment]
> Firstly, I ran `PYTHONPATH=. python optimization/main.py data_gen/generator=bigbigan name=NAME`. And then, I ran `PYTHONPATH=. python segmentation/generate_and_save.py \ name=NAME \ data_gen=generated \ data_gen/generator=bigbigan \ data_gen.checkpoint="YOUR_OPTIMIZATION_DIR_FROM_ABOVE/latest.pth" \ data_gen.save_dir="YOUR_OUTPUT_DIR" \ data_gen.save_size=1000000 \ data_gen.kwargs.batch_size=1 \ data_gen.kwargs.generation_batch_size=128` When I ran `PYTHONPATH=. python segmentation/main.py \ name=NAME \ data_gen=saved \ data_gen.data.root="YOUR_OUTPUT_DIR_FROM_ABOVE"` An error occurred. The error is: `Traceback (most recent call last): File "segmentation/main.py", line 98, in main kwargs = dict(images_dir=_cfg.images_dir, labels_dir=_cfg.labels_dir, omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable '/raid/name/gaochengli/segmentation/src/images' not found" full_key: data_seg.data[0].images_dir object_type=dict` According to what you wrote, I modified the root (config/segment.yaml on line 19). Just like this "/raid/name/gaochengli/segmentation/src/images". And the folder contains all data sets,whose name is images. I wonder why such a mistake happened.

Have you fixed this bug
